import logging
import database

logger = logging.getLogger(__name__)

T = {
    "zh": {
        "main_menu": "请选择功能：",
        "channel_btn": "频道",
        "group_btn": "群组",
        "post_fast_btn": "快速发帖",
        "pro_btn": "高级版",
        "clone_btn": "克隆",
        "timezone_btn": "时区",
        "language_btn": "语言",
        "help_channel_btn": "帮助频道",
        "add_channel_btn": "添加频道",
        "add_group_btn": "添加群组",
        "private_manage_btn": "进入私聊管理",
        "prev_page": "上一页",
        "next_page": "下一页",
        "dingshi_btn": "定时消息",
        "autobutton_btn": "自动按钮",
        "permission_btn": "控制权限",
        "autodelete_btn": "自动删除",
        "back_channel_list": "返回频道列表",
        "back_group_list": "返回群组列表",
        "verify_btn": "进群验证",
        "welcome_btn": "进群欢迎",
        "points_btn": "积分管理",
        "censor_btn": "违禁词",
        "night_btn": "夜间模式",
        "lottery_btn": "抽奖",
        "card_btn": "名片系统",
        "ai_btn": "AI 助手",
        "back_group_manage": "返回群组管理",
        "status_label": "状态:",
        "enable_btn": "开启",
        "disable_btn": "关闭",
        "mode_label": "模式:",
        "button_mode": "按钮模式",
        "math_mode": "数学题",
        "captcha_mode": "验证码",
        "verify_dur_label": "验证时长:",
        "1_minute": "1分钟",
        "5_minutes": "5分钟",
        "10_minutes": "10分钟",
        "timeout_pen_label": "超时惩罚:",
        "mute_penalty": "禁言",
        "kick_penalty": "踢出",
        "func_status_label": "功能状态:",
        "points_per_msg_label": "每条消息积分:",
        "0_points": "0分",
        "1_point": "1分",
        "2_points": "2分",
        "5_points": "5分",
        "filter_stickers_label": "过滤贴纸:",
        "checkin_del_label": "签到消息删除:",
        "no_delete": "不删",
        "10_seconds": "10秒",
        "30_seconds": "30秒",
        "timezone_btn": "时区",
        "language_btn": "语言",
        "help_btn": "帮助频道",
        "back_main": "返回主菜单",
        "back": "返回",
        "back_list": "返回列表",
        "cancel": "取消",
        "confirm": "确认",
        "save": "保存",
        "delete": "删除",
        "delete_short": "删",
        "edit": "修改",
        "add": "添加",
        "enable": "开启",
        "disable": "关闭",
        "on": "开",
        "off": "关",
        "skip": "跳过此步",
        "clear": "清空",
        "clear_media": "清空媒体",
        "preview": "预览消息",
        "share": "分享",
        "status": "状态",
        "type": "类型",
        "name_label": "名称:",
        "keyword_label": "关键词:",
        "text_label": "文本:",
        "media_label": "媒体:",
        "btn_label": "按钮:",
        "inline_usage": "内联用法：",
        "edit_text_btn": "修改文本",
        "edit_media_btn": "修改媒体",
        "edit_btn_btn": "修改按钮",
        "edit_info_btn": "修改信息",
        "close_btn": "关闭",
        "open_btn": "开启",
        "del_msg_label": "删除消息(分钟)",
        "del_last_btn": "删除上一条",
        "ai_chat_label": "AI聊天:",
        "ai_trigger_label": "触发词:",
        "ai_set_prompt_btn": "设置提示词",
        "ai_audit_label": "AI审计:",
        "ai_penalty_label": "审计处罚:",
        "ai_delete_only": "仅删除",
        "ai_mute_1h": "禁言1小时",
        "ai_kick": "踢出",
        "ai_ban": "封禁",
        "unknown": "未知",
        "error": "出错了",
        "success": "操作成功",
        "failed": "操作失败",
        "not_admin": "只有管理员才能执行此操作。",
        "admin_only": "只有管理员才能管理",
        "lang_changed": "语言已切换为简体中文",
        "settings": "设置",
        "manage": "管理",
        "yes": "是",
        "no": "否",
        "timezone_changed": "时区已更新为",
        "timezone_title": "时区设置",
        "next_page": "下一页",
        "prev_page": "上一页",
        "add_channel": "添加频道",
        "add_group": "添加群组",
        "group_manage_panel": "群组管理面板",
        "channel_manage_panel": "频道管理",
        "group_verify": "进群验证",
        "group_welcome": "进群欢迎",
        "group_points": "积分管理",
        "group_dingshi": "定时消息",
        "group_censor": "违禁词",
        "group_night": "夜间模式",
        "group_lottery": "抽奖",
        "dingshi_title": "定时消息管理",
        "dingshi_desc": "设置后，机器人将在指定时间自动发送消息到本群。",
        "dingshi_no_data": "暂无定时消息，点击下方按钮添加。",
        "dingshi_add": "添加定时消息",
        "dingshi_back_list": "返回定时列表",
        "dingshi_detail": "定时消息详情",
        "dingshi_edit_text": "修改文本",
        "dingshi_edit_media": "修改媒体",
        "dingshi_edit_btn": "修改按钮",
        "dingshi_edit_time": "修改时间",
        "dingshi_del": "删除此定时",
        "dingshi_toggle_on": "关闭",
        "dingshi_toggle_off": "开启",
        "dingshi_step_time": "请发送 发送时间 和 发送周期",
        "dingshi_step_text": "设置消息文本",
        "dingshi_step_media": "设置媒体附件",
        "dingshi_step_btn": "设置按钮",
        "dingshi_time_updated": "发送时间已更新！",
        "dingshi_created": "时间设置成功！",
        "weijinci_title": "违禁词管理",
        "weijinci_desc": "设置违禁词后，包含违禁词的消息将被自动处理。",
        "weijinci_no_data": "暂无违禁词，点击下方按钮添加。",
        "weijinci_add": "添加违禁词",
        "weijinci_select_penalty": "请选择处罚方式：",
        "weijinci_penalty_delete": "仅删除消息",
        "weijinci_penalty_mute": "禁言",
        "weijinci_penalty_kick": "踢出群组",
        "weijinci_penalty_ban": "永久封禁",
        "weijinci_edit_penalty": "修改处罚方式",
        "weijinci_enter_word": "请发送要屏蔽的违禁词：",
        "weijinci_added": "已添加",
        "weijinci_deleted": "已删除",
        "weijinci_updated": "已更新",
        "weijinci_toggled": "已切换",
        "night_title": "夜间模式",
        "night_desc": "限制群组内用户在指定时间段的发言",
        "night_warning": "提示: 修改时间段或者时区后，请重新开启夜间模式才能生效",
        "night_mode": "模式: 全员禁言",
        "night_period": "时间段",
        "night_notify": "开始和结束通知",
        "night_curr_time": "当前时间",
        "night_enable_btn": "开启夜间模式",
        "night_disable_btn": "关闭夜间模式",
        "night_set_start": "设置开始",
        "night_set_end": "设置结束",
        "night_notify_btn": "通知",
        "night_started": "夜间模式已开始",
        "night_ended": "夜间模式已结束",
        "night_desc_started": "全员禁言中",
        "night_desc_ended": "全员禁言已解除。",
        "night_admin_unaffected": "管理员不受影响。",
        "choujiang_title": "抽奖管理",
        "choujiang_stats": "创建的抽奖次数",
        "choujiang_drawn": "已开奖",
        "choujiang_active": "未开奖",
        "choujiang_cancelled": "取消",
        "choujiang_create": "创建抽奖",
        "choujiang_settings": "抽奖设置",
        "choujiang_select_type": "请选择抽奖类型：",
        "choujiang_select_method": "请选择开奖方式：",
        "choujiang_type_general": "通用抽奖",
        "choujiang_type_points": "积分抽奖",
        "choujiang_type_activity": "群活跃抽奖",
        "choujiang_type_dice": "骰子点数抽奖",
        "choujiang_type_report": "报道抽奖",
        "choujiang_method_count": "到达人数开奖",
        "choujiang_method_time": "到达时间开奖",
        "choujiang_step_title": "输入抽奖标题",
        "choujiang_step_winners": "设置中奖人数",
        "choujiang_step_drawval": "设置开奖条件",
        "choujiang_step_cost": "设置参与积分",
        "choujiang_step_confirm": "创建抽奖确认",
        "choujiang_add_prize": "添加奖品",
        "choujiang_del_prize": "删除最后奖品",
        "choujiang_confirm_create": "确认创建",
        "choujiang_early_draw": "提前开奖",
        "choujiang_cancel": "取消抽奖",
        "choujiang_result": "抽奖结果",
        "choujiang_winners": "中奖名单",
        "choujiang_participants": "参与人数",
        "choujiang_enter": "参与抽奖",
        "choujiang_points_enter": "积分参与",
        "choujiang_already_entered": "你已经参与过了！",
        "choujiang_ended": "该抽奖已结束或不存在",
        "choujiang_insufficient_points": "积分不足",
        "choujiang_entered_ok": "参与成功！",
        "choujiang_pin_lottery": "发布置顶",
        "choujiang_pin_result": "结果置顶",
        "choujiang_del_entry": "删除口令",
        "choujiang_push_channel": "推送频道",
        "kuaisu_title": "快捷发布",
        "kuaisu_desc": "设置帖子文字、媒体、按钮等参数",
        "kuaisu_no_data": "暂无消息模板，点击下方按钮添加。",
        "kuaisu_add": "添加快捷消息",
        "kuaisu_detail": "快捷消息详情",
        "kuaisu_edit_text": "编辑文本",
        "kuaisu_edit_media": "编辑媒体",
        "kuaisu_edit_btn": "编辑按钮",
        "kuaisu_edit_info": "修改信息",
        "kuaisu_created": "已创建",
        "kuaisu_updated": "已更新",
        "kuaisu_deleted": "已删除",
        "kuaisu_enter_name": "请发送快捷消息的名称：",
        "kuaisu_select_group": "请选择要管理的群组：",
        "autobtn_title": "自动按钮",
        "autobtn_desc": "检测到频道新消息后自动编辑添加按钮",
        "autobtn_enabled": "已开启",
        "autobtn_disabled": "已关闭",
        "autobtn_edit": "编辑按钮",
        "autobtn_empty": "未设置",
        "start_message": '<tg-emoji emoji-id="5203948303305158848">🍷</tg-emoji>嗨，{USER} !\n\n<tg-emoji emoji-id="5929192117220937925">⭐️</tg-emoji>{BOT_USERNAME} 能帮你便捷安全地管理频道和群组，是TG上领先的管理的机器人之一！\n\n<tg-emoji emoji-id="5866185084427572234">🤖</tg-emoji>请赋予我频道/群组管理员权限！\n\n<tg-emoji emoji-id="6093793027988393802">😀</tg-emoji><a href="https://t.me/JB7777_bot?start=496953"> 金博娱乐 · 真正懂玩家的平台</a>',
        "add_pindao": '<tg-emoji emoji-id="5323476770706432095">📍</tg-emoji> 指南\n\n想要在频道中使用 {BOT_USERNAME} 的功能，只需把这个机器人添加到您的频道并授予发送消息等权限。\n\n<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji> 注意: 如果把这个Bot添加到频道后没有来自这个机器人任何通知，您需要删除并重新添加Bot为管理员。',
        "add_qun": '<tg-emoji emoji-id="5323476770706432095">📍</tg-emoji> 指南\n\n想要在群组中使用 {BOT_USERNAME} 的功能，只需把这个机器人添加到您的群组并授予管理消息等权限。\n\n<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji> 注意: 如果把这个Bot添加到群组后没有来自这个机器人任何通知，您需要删除并重新添加Bot为管理员。',
        "choose_lang": '<tg-emoji emoji-id="5879585266426973039">🌐</tg-emoji> 选择语言\n\n当前语言：{LANG}\n\nSelect your language:',
        "timezone_message": '<tg-emoji emoji-id="5258419835922030550">🕒</tg-emoji> 设置时区\n\n当前时区：<b>{TIMEZONE}</b>\n\n选择你的时区：',
    },
    "zh-TW": {
        "main_menu": "請選擇功能：",
        "channel_btn": "頻道",
        "group_btn": "群組",
        "post_fast_btn": "快速發文",
        "timezone_btn": "時區",
        "language_btn": "語言",
        "help_btn": "幫助頻道",
        "back_main": "返回主選單",
        "back": "返回",
        "back_list": "返回列表",
        "cancel": "取消",
        "confirm": "確認",
        "save": "儲存",
        "delete": "刪除",
        "delete_short": "刪",
        "edit": "修改",
        "add": "新增",
        "enable": "開啟",
        "disable": "關閉",
        "on": "開",
        "off": "關",
        "skip": "跳過此步驟",
        "clear": "清除",
        "clear_media": "清除媒體",
        "preview": "預覽訊息",
        "share": "分享",
        "status": "狀態",
        "type": "類型",
        "name_label": "名稱:",
        "keyword_label": "關鍵詞:",
        "text_label": "文字:",
        "media_label": "媒體:",
        "btn_label": "按鈕:",
        "inline_usage": "內聯用法：",
        "edit_text_btn": "修改文字",
        "edit_media_btn": "修改媒體",
        "edit_btn_btn": "修改按鈕",
        "edit_info_btn": "修改資訊",
        "close_btn": "關閉",
        "open_btn": "開啟",
        "del_msg_label": "刪除訊息(分鐘)",
        "del_last_btn": "刪除上一條",
        "ai_chat_label": "AI聊天:",
        "ai_trigger_label": "觸發詞:",
        "ai_set_prompt_btn": "設定提示詞",
        "ai_audit_label": "AI審計:",
        "ai_penalty_label": "審計處罰:",
        "ai_delete_only": "僅刪除",
        "ai_mute_1h": "禁言1小時",
        "ai_kick": "踢出",
        "ai_ban": "封禁",
        "unknown": "未知",
        "error": "發生錯誤",
        "success": "操作成功",
        "failed": "操作失敗",
        "not_admin": "只有管理員才能執行此操作。",
        "admin_only": "只有管理員才能管理",
        "lang_changed": "語言已切換為繁體中文",
        "settings": "設定",
        "manage": "管理",
        "yes": "是",
        "no": "否",
        "timezone_changed": "時區已更新為",
        "timezone_title": "時區設定",
        "next_page": "下一頁",
        "prev_page": "上一頁",
        "add_channel": "新增頻道",
        "add_group": "新增群組",
        "group_manage_panel": "群組管理面板",
        "channel_manage_panel": "頻道管理",
        "group_verify": "進群驗證",
        "group_welcome": "進群歡迎",
        "group_points": "積分管理",
        "group_dingshi": "定時訊息",
        "group_censor": "違禁詞",
        "group_night": "夜間模式",
        "group_lottery": "抽獎",
        "dingshi_title": "定時訊息管理",
        "dingshi_desc": "設定後，機器人將在指定時間自動發送訊息到本群。",
        "dingshi_no_data": "暫無定時訊息，點擊下方按鈕新增。",
        "dingshi_add": "新增定時訊息",
        "dingshi_back_list": "返回定時列表",
        "dingshi_detail": "定時訊息詳情",
        "dingshi_edit_text": "修改文字",
        "dingshi_edit_media": "修改媒體",
        "dingshi_edit_btn": "修改按鈕",
        "dingshi_edit_time": "修改時間",
        "dingshi_del": "刪除此定時",
        "dingshi_toggle_on": "關閉",
        "dingshi_toggle_off": "開啟",
        "dingshi_step_time": "請發送 發送時間 和 發送週期",
        "dingshi_step_text": "設定訊息文字",
        "dingshi_step_media": "設定媒體附件",
        "dingshi_step_btn": "設定按鈕",
        "dingshi_time_updated": "發送時間已更新！",
        "dingshi_created": "時間設定成功！",
        "weijinci_title": "違禁詞管理",
        "weijinci_desc": "設定違禁詞後，包含違禁詞的訊息將被自動處理。",
        "weijinci_no_data": "暫無違禁詞，點擊下方按鈕新增。",
        "weijinci_add": "新增違禁詞",
        "weijinci_select_penalty": "請選擇處罰方式：",
        "weijinci_penalty_delete": "僅刪除訊息",
        "weijinci_penalty_mute": "禁言",
        "weijinci_penalty_kick": "踢出群組",
        "weijinci_penalty_ban": "永久封禁",
        "weijinci_edit_penalty": "修改處罰方式",
        "weijinci_enter_word": "請發送要屏蔽的違禁詞：",
        "weijinci_added": "已新增",
        "weijinci_deleted": "已刪除",
        "weijinci_updated": "已更新",
        "weijinci_toggled": "已切換",
        "night_title": "夜間模式",
        "night_desc": "限制群組內使用者在指定時間段的發言",
        "night_warning": "提示: 修改時間段或者時區後，請重新開啟夜間模式才能生效",
        "night_mode": "模式: 全員禁言",
        "night_period": "時間段",
        "night_notify": "開始和結束通知",
        "night_curr_time": "當前時間",
        "night_enable_btn": "開啟夜間模式",
        "night_disable_btn": "關閉夜間模式",
        "night_set_start": "設定開始",
        "night_set_end": "設定結束",
        "night_notify_btn": "通知",
        "night_started": "夜間模式已開始",
        "night_ended": "夜間模式已結束",
        "night_desc_started": "全員禁言中",
        "night_desc_ended": "全員禁言已解除。",
        "night_admin_unaffected": "管理員不受影響。",
        "choujiang_title": "抽獎管理",
        "choujiang_stats": "建立的抽獎次數",
        "choujiang_drawn": "已開獎",
        "choujiang_active": "未開獎",
        "choujiang_cancelled": "取消",
        "choujiang_create": "建立抽獎",
        "choujiang_settings": "抽獎設定",
        "choujiang_select_type": "請選擇抽獎類型：",
        "choujiang_select_method": "請選擇開獎方式：",
        "choujiang_type_general": "通用抽獎",
        "choujiang_type_points": "積分抽獎",
        "choujiang_type_activity": "群活躍抽獎",
        "choujiang_type_dice": "骰子點數抽獎",
        "choujiang_type_report": "報到抽獎",
        "choujiang_method_count": "到達人數開獎",
        "choujiang_method_time": "到達時間開獎",
        "choujiang_step_title": "輸入抽獎標題",
        "choujiang_step_winners": "設定中獎人數",
        "choujiang_step_drawval": "設定開獎條件",
        "choujiang_step_cost": "設定參與積分",
        "choujiang_step_confirm": "建立抽獎確認",
        "choujiang_add_prize": "新增獎品",
        "choujiang_del_prize": "刪除最後獎品",
        "choujiang_confirm_create": "確認建立",
        "choujiang_early_draw": "提前開獎",
        "choujiang_cancel": "取消抽獎",
        "choujiang_result": "抽獎結果",
        "choujiang_winners": "中獎名單",
        "choujiang_participants": "參與人數",
        "choujiang_enter": "參與抽獎",
        "choujiang_points_enter": "積分參與",
        "choujiang_already_entered": "你已經參與過了！",
        "choujiang_ended": "該抽獎已結束或不存在",
        "choujiang_insufficient_points": "積分不足",
        "choujiang_entered_ok": "參與成功！",
        "choujiang_pin_lottery": "發佈置頂",
        "choujiang_pin_result": "結果置頂",
        "choujiang_del_entry": "刪除口令",
        "choujiang_push_channel": "推送頻道",
        "kuaisu_title": "快捷發佈",
        "kuaisu_desc": "設定貼文文字、媒體、按鈕等參數",
        "kuaisu_no_data": "暫無訊息範本，點擊下方按鈕新增。",
        "kuaisu_add": "新增快捷訊息",
        "kuaisu_detail": "快捷訊息詳情",
        "kuaisu_edit_text": "編輯文字",
        "kuaisu_edit_media": "編輯媒體",
        "kuaisu_edit_btn": "編輯按鈕",
        "kuaisu_edit_info": "修改資訊",
        "kuaisu_created": "已建立",
        "kuaisu_updated": "已更新",
        "kuaisu_deleted": "已刪除",
        "kuaisu_enter_name": "請發送快捷訊息的名稱：",
        "kuaisu_select_group": "請選擇要管理的群組：",
        "autobtn_title": "自動按鈕",
        "autobtn_desc": "偵測到頻道新訊息後自動編輯新增按鈕",
        "autobtn_enabled": "已開啟",
        "autobtn_disabled": "已關閉",
        "autobtn_edit": "編輯按鈕",
        "autobtn_empty": "未設定",
        "start_message": '<tg-emoji emoji-id="5203948303305158848">🍷</tg-emoji>嗨，{USER} !\n\n<tg-emoji emoji-id="5929192117220937925">⭐️</tg-emoji>{BOT_USERNAME} 能幫助你便捷安全地管理頻道和群組，是TG上領先的管理機器人之一！\n\n<tg-emoji emoji-id="5866185084427572234">🤖</tg-emoji>請賦予我頻道/群組管理員權限！\n\n<tg-emoji emoji-id="6093793027988393802">😀</tg-emoji><a href="https://t.me/JB7777_bot?start=496953">金博娱乐 · 真正懂玩家的平台</a>',
        "add_pindao": '<tg-emoji emoji-id="5323476770706432095">📍</tg-emoji> 指南\n\n想要在頻道中使用 {BOT_USERNAME} 的功能，只需把這個機器人添加到您的頻道並授予發送訊息等權限。\n\n<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji> 注意: 如果把這個Bot添加到頻道後沒有來自這個機器人的任何通知，您需要刪除並重新添加Bot為管理員。',
        "add_qun": '<tg-emoji emoji-id="5323476770706432095">📍</tg-emoji> 指南\n\n想要在群組中使用 {BOT_USERNAME} 的功能，只需把這個機器人添加到您的群組並授予管理訊息等權限。\n\n<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji> 注意: 如果把這個Bot添加到群組後沒有來自這個機器人的任何通知，您需要刪除並重新添加Bot為管理員。',
        "choose_lang": '<tg-emoji emoji-id="5879585266426973039">🌐</tg-emoji> 選擇語言\n\n當前語言：{LANG}\n\nSelect your language:',
        "timezone_message": '<tg-emoji emoji-id="5258419835922030550">🕒</tg-emoji> 設定時區\n\n當前時區：<b>{TIMEZONE}</b>\n\n選擇你的時區：',
    },
    "en": {
        "main_menu": "Select a function:",
        "channel_btn": "Channels",
        "group_btn": "Groups",
        "post_fast_btn": "Quick Post",
        "timezone_btn": "Timezone",
        "language_btn": "Language",
        "help_btn": "Help Channel",
        "back_main": "Back to Main Menu",
        "back": "Back",
        "back_list": "Back to List",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "save": "Save",
        "delete": "Delete",
        "delete_short": "Del",
        "edit": "Edit",
        "add": "Add",
        "enable": "Enable",
        "disable": "Disable",
        "on": "On",
        "off": "Off",
        "skip": "Skip",
        "clear": "Clear",
        "clear_media": "Clear Media",
        "preview": "Preview",
        "share": "Share",
        "status": "Status",
        "type": "Type",
        "name_label": "Name:",
        "keyword_label": "Keyword:",
        "text_label": "Text:",
        "media_label": "Media:",
        "btn_label": "Buttons:",
        "inline_usage": "Inline:",
        "edit_text_btn": "Edit Text",
        "edit_media_btn": "Edit Media",
        "edit_btn_btn": "Edit Buttons",
        "edit_info_btn": "Edit Info",
        "close_btn": "Close",
        "open_btn": "Open",
        "del_msg_label": "Delete Msg (min)",
        "del_last_btn": "Delete Last",
        "ai_chat_label": "AI Chat:",
        "ai_trigger_label": "Trigger:",
        "ai_set_prompt_btn": "Set Prompt",
        "ai_audit_label": "AI Audit:",
        "ai_penalty_label": "Audit Penalty:",
        "ai_delete_only": "Delete Only",
        "ai_mute_1h": "Mute 1h",
        "ai_kick": "Kick",
        "ai_ban": "Ban",
        "unknown": "Unknown",
        "error": "Error",
        "success": "Success",
        "failed": "Failed",
        "not_admin": "Only admins can perform this action.",
        "admin_only": "Only admins can manage",
        "lang_changed": "Language changed to English",
        "settings": "Settings",
        "manage": "Manage",
        "yes": "Yes",
        "no": "No",
        "timezone_changed": "Timezone changed to",
        "timezone_title": "Timezone Settings",
        "next_page": "Next",
        "prev_page": "Previous",
        "add_channel": "Add Channel",
        "add_group": "Add Group",
        "group_manage_panel": "Group Management",
        "channel_manage_panel": "Channel Management",
        "group_verify": "Verification",
        "group_welcome": "Welcome",
        "group_points": "Points",
        "group_dingshi": "Scheduled Msg",
        "group_censor": "Banned Words",
        "group_night": "Night Mode",
        "group_lottery": "Lottery",
        "dingshi_title": "Scheduled Messages",
        "dingshi_desc": "Bot will automatically send messages at the specified time.",
        "dingshi_no_data": "No scheduled messages yet.",
        "dingshi_add": "Add Message",
        "dingshi_back_list": "Back to List",
        "dingshi_detail": "Message Details",
        "dingshi_edit_text": "Edit Text",
        "dingshi_edit_media": "Edit Media",
        "dingshi_edit_btn": "Edit Buttons",
        "dingshi_edit_time": "Edit Time",
        "dingshi_del": "Delete",
        "dingshi_toggle_on": "Disable",
        "dingshi_toggle_off": "Enable",
        "dingshi_step_time": "Please send time and schedule",
        "dingshi_step_text": "Set message text",
        "dingshi_step_media": "Set media attachment",
        "dingshi_step_btn": "Set buttons",
        "dingshi_time_updated": "Time updated!",
        "dingshi_created": "Time set!",
        "weijinci_title": "Banned Words",
        "weijinci_desc": "Messages containing banned words will be automatically processed.",
        "weijinci_no_data": "No banned words yet.",
        "weijinci_add": "Add Word",
        "weijinci_select_penalty": "Select penalty:",
        "weijinci_penalty_delete": "Delete Message",
        "weijinci_penalty_mute": "Mute",
        "weijinci_penalty_kick": "Kick",
        "weijinci_penalty_ban": "Ban",
        "weijinci_edit_penalty": "Change Penalty",
        "weijinci_enter_word": "Enter the banned word:",
        "weijinci_added": "Added",
        "weijinci_deleted": "Deleted",
        "weijinci_updated": "Updated",
        "weijinci_toggled": "Toggled",
        "night_title": "Night Mode",
        "night_desc": "Restrict users from speaking during specified hours",
        "night_warning": "Note: After changing time period or timezone, please re-enable night mode.",
        "night_mode": "Mode: Mute All",
        "night_period": "Time Period",
        "night_notify": "Start/End Notification",
        "night_curr_time": "Current Time",
        "night_enable_btn": "Enable Night Mode",
        "night_disable_btn": "Disable Night Mode",
        "night_set_start": "Set Start",
        "night_set_end": "Set End",
        "night_notify_btn": "Notify",
        "night_started": "Night Mode Started",
        "night_ended": "Night Mode Ended",
        "night_desc_started": "All members are muted",
        "night_desc_ended": "Mute has been lifted.",
        "night_admin_unaffected": "Admins are not affected.",
        "choujiang_title": "Lottery",
        "choujiang_stats": "Total Created",
        "choujiang_drawn": "Drawn",
        "choujiang_active": "Active",
        "choujiang_cancelled": "Cancelled",
        "choujiang_create": "Create Lottery",
        "choujiang_settings": "Settings",
        "choujiang_select_type": "Select lottery type:",
        "choujiang_select_method": "Select draw method:",
        "choujiang_type_general": "General",
        "choujiang_type_points": "Points",
        "choujiang_type_activity": "Activity",
        "choujiang_type_dice": "Dice",
        "choujiang_type_report": "Report",
        "choujiang_method_count": "By Participant Count",
        "choujiang_method_time": "By Time",
        "choujiang_step_title": "Enter title",
        "choujiang_step_winners": "Set winner count",
        "choujiang_step_drawval": "Set draw condition",
        "choujiang_step_cost": "Set entry cost",
        "choujiang_step_confirm": "Confirm",
        "choujiang_add_prize": "Add Prize",
        "choujiang_del_prize": "Remove Last",
        "choujiang_confirm_create": "Confirm & Create",
        "choujiang_early_draw": "Draw Now",
        "choujiang_cancel": "Cancel Lottery",
        "choujiang_result": "Lottery Result",
        "choujiang_winners": "Winners",
        "choujiang_participants": "Participants",
        "choujiang_enter": "Enter",
        "choujiang_points_enter": "Enter with Points",
        "choujiang_already_entered": "You have already entered!",
        "choujiang_ended": "This lottery has ended or does not exist",
        "choujiang_insufficient_points": "Insufficient points",
        "choujiang_entered_ok": "Entered successfully!",
        "choujiang_pin_lottery": "Pin Lottery",
        "choujiang_pin_result": "Pin Result",
        "choujiang_del_entry": "Delete Entry",
        "choujiang_push_channel": "Push Channel",
        "kuaisu_title": "Quick Post",
        "kuaisu_desc": "Configure post text, media, buttons etc.",
        "kuaisu_no_data": "No templates yet.",
        "kuaisu_add": "Add Template",
        "kuaisu_detail": "Template Details",
        "kuaisu_edit_text": "Edit Text",
        "kuaisu_edit_media": "Edit Media",
        "kuaisu_edit_btn": "Edit Buttons",
        "kuaisu_edit_info": "Edit Info",
        "kuaisu_created": "Created",
        "kuaisu_updated": "Updated",
        "kuaisu_deleted": "Deleted",
        "kuaisu_enter_name": "Enter template name:",
        "kuaisu_select_group": "Select a group to manage:",
        "autobtn_title": "Auto Button",
        "autobtn_desc": "Automatically add buttons to new channel posts",
        "autobtn_enabled": "Enabled",
        "autobtn_disabled": "Disabled",
        "autobtn_edit": "Edit Buttons",
        "autobtn_empty": "Not set",
        "start_message": '<tg-emoji emoji-id="5203948303305158848">🍷</tg-emoji>Hi, {USER}!\n\n<tg-emoji emoji-id="5929192117220937925">⭐️</tg-emoji>{BOT_USERNAME} helps you manage channels and groups securely — one of the top management bots on Telegram!\n\n<tg-emoji emoji-id="5866185084427572234">🤖</tg-emoji>Please grant me channel/group admin permissions!\n\n<tg-emoji emoji-id="6093793027988393802">😀</tg-emoji><a href="https://t.me/JB7777_bot?start=496953">金博娱乐 · 真正懂玩家的平台</a>',
        "add_pindao": '<tg-emoji emoji-id="5323476770706432095">📍</tg-emoji> Guide\n\nTo use {BOT_USERNAME} in a channel, add this bot to your channel and grant post/edit/delete message permissions.\n\n<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji> Note: If you don\'t receive any notification after adding, please remove and re-add the bot as admin.',
        "add_qun": '<tg-emoji emoji-id="5323476770706432095">📍</tg-emoji> Guide\n\nTo use {BOT_USERNAME} in a group, add this bot to your group and grant message management permissions.\n\n<tg-emoji emoji-id="5447644880824181073">⚠️</tg-emoji> Note: If you don\'t receive any notification after adding, please remove and re-add the bot as admin.',
        "choose_lang": '<tg-emoji emoji-id="5879585266426973039">🌐</tg-emoji> Select Language\n\nCurrent: {LANG}\n\nSelect your language:',
        "timezone_message": '<tg-emoji emoji-id="5258419835922030550">🕒</tg-emoji> Set Timezone\n\nCurrent: <b>{TIMEZONE}</b>\n\nSelect your timezone:',
    }
}

LANG_NAMES = {"zh": "简体中文", "zh-TW": "繁體中文", "en": "English"}
DEFAULT_LANG = "zh"

_user_lang_cache = {}


async def get_user_lang(user_id: int) -> str:
    if user_id in _user_lang_cache:
        return _user_lang_cache[user_id]
    try:
        async with database.db_pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute("SELECT language FROM users WHERE user_id = %s", (user_id,))
                row = await cur.fetchone()
                if row and row[0]:
                    _user_lang_cache[user_id] = row[0]
                    return row[0]
    except Exception:
        pass
    return DEFAULT_LANG


async def set_user_lang(user_id: int, lang: str):
    _user_lang_cache[user_id] = lang
    try:
        async with database.db_pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute(
                    "INSERT INTO users (user_id, language) VALUES (%s, %s) ON DUPLICATE KEY UPDATE language = VALUES(language)",
                    (user_id, lang))
    except Exception as e:
        logger.error(f"set_user_lang err: {e}")


async def t(user_id: int, key: str, **kwargs) -> str:
    lang = await get_user_lang(user_id)
    text = T.get(lang, T[DEFAULT_LANG]).get(key, T[DEFAULT_LANG].get(key, key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except Exception:
            pass
    return text


def t_sync(lang: str, key: str, **kwargs) -> str:
    text = T.get(lang, T[DEFAULT_LANG]).get(key, T[DEFAULT_LANG].get(key, key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except Exception:
            pass
    return text


async def tb(user_id: int, key: str, **kwargs) -> str:
    """Shortcut for button text translation."""
    return await t(user_id, key, **kwargs)


def get_template(key: str, lang: str = DEFAULT_LANG, **kwargs) -> str:
    """Get a template message by key and language (sync, no user lookup)."""
    text = T.get(lang, T[DEFAULT_LANG]).get(key, T[DEFAULT_LANG].get(key, key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except Exception:
            pass
    return text
